#!/bin/tcsh

: Takes fMRI NII/AFNI filename as input and compute WM, CSF masks for regression
: Inputs: $1 Directory name
:         $2 subject name
:         input file is obtained from OUTFILE  variable
: Output: Output afni file name
:
: Author: Saurabh
: April 23 2020, PPRC @ UBC




echo "[Main] Despiking fMRI  data ..."

if ($#argv != 2) then
    echo "[Error] Insufficient number of input arguments. Expected 2 got $#argv"
    exit 1
endif

: check if file exists
if ( ! -d "$1" ) then
    echo "[Error] Parent directory $1 not found "
    exit 1
endif

if ( ! -d "$1/$2" ) then
    echo "[Error] Subject directory $1/$2 not found "
    exit 1
endif

if ( ! -f "$output_dir/$OUTFILE" ) then
    echo "[Error] Input file $1/$2/$OUTFILE not found "
    exit 1
endif

set file=$OUTFILE


if ( ! -f "$output_dir//ROIPC.FSvent.1D" ) then


: Generating CSF, GM and WM masks
: register the masks to the func space
echo flirt -interp nearestneighbour -in $1/freesurfer/$2/surf/SUMA/fs_ap_wm.nii.gz -ref $output_dir/${base}_reference_$minindex".nii" -applyxfm -init $output_dir/struct2func.mat -out $output_dir/fs_ap_wm_infunc.nii.gz
flirt -interp nearestneighbour -in $1/freesurfer/$2/surf/SUMA/fs_ap_wm.nii.gz -ref $output_dir/${base}_reference_$minindex".nii" -applyxfm -init $output_dir/struct2func.mat -out $output_dir/fs_ap_wm_infunc.nii.gz
if ( "$?" == "1" ) then
	echo "[Error] flirt for WM mask failed with error"
	exit 1
endif

echo flirt -interp nearestneighbour -in $1/freesurfer/$2/surf/SUMA/fs_ap_latvent.nii.gz -ref $output_dir/${base}_reference_$minindex".nii" -applyxfm -init $output_dir/struct2func.mat -out $output_dir/fs_ap_latvent_infunc.nii.gz
flirt -interp nearestneighbour -in $1/freesurfer/$2/surf/SUMA/fs_ap_latvent.nii.gz -ref $output_dir/${base}_reference_$minindex".nii" -applyxfm -init $output_dir/struct2func.mat -out $output_dir/fs_ap_latvent_infunc.nii.gz
if ( "$?" == "1" ) then
	echo "[Error] flirt for CSF Mask failed with error"
	exit 1
endif


echo "[Debug] Eroding the masks generated by FS"
: erode mask wm and csf
echo fslmaths $output_dir/fs_ap_wm_infunc.nii.gz -kernel box 3x3x3 -ero $output_dir/'fs_ap_wm_erode.nii.gz'
fslmaths $output_dir/fs_ap_wm_infunc.nii.gz -kernel box 3x3x3 -ero $output_dir/'fs_ap_wm_erode.nii.gz'
if ( "$?" == "1" ) then
	echo "[Error] Eroding WM Mask failed with error"
	exit 1
endif
echo fslmaths $output_dir/fs_ap_latvent_infunc.nii.gz -kernel box 3x3x3 -ero $output_dir/'fs_ap_latvent_erode.nii.gz'
fslmaths $output_dir/fs_ap_latvent_infunc.nii.gz -kernel box 3x3x3 -ero $output_dir/'fs_ap_latvent_erode.nii.gz'
if ( "$?" == "1" ) then
	echo "[Error] Eroding CSF Mask failed with error"
	exit 1
endif


echo 3dmaskave -quiet -mask  $output_dir/fs_ap_wm_erode.nii.gz $output_dir/$OUTFILE  savedto  $output_dir/ROIPC.FSvent.1D
3dmaskave -quiet -mask  $output_dir/fs_ap_wm_erode.nii.gz $output_dir/$OUTFILE  > $output_dir/ROIPC.FSvent.1D
if ( "$?" == "1" ) then
	echo "[Error] Extract WM Mask failed with error"
	exit 1
endif
echo 3dmaskave -quiet -mask $output_dir/fs_ap_latvent_erode.nii.gz $output_dir/$OUTFILE  savedto $output_dir/CSF_Timecourse.1D
3dmaskave -quiet -mask $output_dir/fs_ap_latvent_erode.nii.gz $output_dir/$OUTFILE  > $output_dir/CSF_Timecourse.1D
if ( "$?" == "1" ) then
	echo "[Error] Extract CSF  Mask failed with error"
	exit 1
endif

else
	echo "[Debug]  WM, CSF masks are already computed"
endif

echo $OUTFILE
